# Generated by Django 3.2.9 on 2021-11-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('origin', models.CharField(max_length=300)),
                ('body_material', models.CharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('neck_material', models.CharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('fingerboard_material', models.CharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('fingerboard_radius', models.IntegerField()),
                ('neck_shape', models.CharField(choices=[('CS', 'C'), ('CC', 'C Chunky'), ('DS', 'D'), ('VH', 'V Hard'), ('VS', 'V Soft'), ('AS', 'Asymmetrical'), ('US', 'U')], max_length=2)),
                ('strings', models.IntegerField(choices=[(6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (12, 'Twelve')])),
                ('frets_quantity', models.CharField(choices=[('NT', '19'), ('TW', '20'), ('TO', '21'), ('TT', '22'), ('TF', '24'), ('OT', 'Other')], max_length=2)),
                ('frets_type', models.CharField(choices=[('RMJ', 'Medium Jumbo'), ('RJJ', 'Jumbo'), ('RXJ', 'Extra Jumbo'), ('SMJ', 'Stainless Medium Jumbo'), ('SJJ', 'Stainless Jumbo'), ('SXJ', 'Stainless Extra Jumbo')], max_length=3)),
                ('scale_length', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.bridge')),
                ('bridge_pickup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_pickup', to='guitars.pickup')),
                ('middle_pickup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_pickup', to='guitars.pickup')),
                ('neck_pickup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neck_pickup', to='guitars.pickup')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
