# Generated by Django 3.2.9 on 2021-12-02 13:30

from django.db import migrations, models
import django.db.models.deletion
import guitarradar.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('url', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('model_name', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
            ],
            options={
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('model_name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('origin', models.CharField(max_length=300)),
                ('body_material', guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('neck_material', guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('construction', models.CharField(choices=[('BO', 'Bolt-on'), ('SN', 'Set neck'), ('NT', 'Neck-thru'), ('ST', 'Set-thru')], max_length=2)),
                ('fingerboard_material', guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2)),
                ('fingerboard_radius', models.CharField(max_length=5)),
                ('neck_shape', models.CharField(choices=[('CS', 'C'), ('CC', 'C Chunky'), ('DS', 'D'), ('VH', 'V Hard'), ('VS', 'V Soft'), ('AS', 'Asymmetrical'), ('US', 'U')], max_length=2)),
                ('strings', models.IntegerField(choices=[(6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (12, 'Twelve')])),
                ('frets_quantity', models.CharField(choices=[('NT', '19'), ('TW', '20'), ('TO', '21'), ('TT', '22'), ('TF', '24'), ('OT', 'Other')], max_length=2)),
                ('frets_type', models.CharField(choices=[('RMJ', 'Medium Jumbo'), ('RJJ', 'Jumbo'), ('RXJ', 'Extra Jumbo'), ('SMJ', 'Stainless Medium Jumbo'), ('SJJ', 'Stainless Jumbo'), ('SXJ', 'Stainless Extra Jumbo')], max_length=3)),
                ('scale_length', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.bridge')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('model_name', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=5000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitars.brand')),
            ],
            options={
                'unique_together': {('brand', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='GuitarPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='guitarradar/guitars/pictures')),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitar_picture', to='guitars.guitar')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guitar',
            name='bridge_pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_pickup', to='guitars.pickup'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='middle_pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middle_pickup', to='guitars.pickup'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='neck_pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neck_pickup', to='guitars.pickup'),
        ),
        migrations.AlterUniqueTogether(
            name='guitar',
            unique_together={('brand', 'model_name')},
        ),
    ]
