# Generated by Django 3.2.9 on 2021-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guitar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bridge',
            unique_together={('brand', 'model_name')},
        ),
        migrations.AlterUniqueTogether(
            name='guitar',
            unique_together={('brand', 'model_name')},
        ),
        migrations.AlterUniqueTogether(
            name='pickup',
            unique_together={('brand', 'model_name')},
        ),
    ]
