# Generated by Django 3.2.9 on 2021-11-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_auto_20211128_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='guitarradar/guitars/pictures')),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitar_picture', to='guitars.guitar')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
