# Generated by Django 3.2.9 on 2021-11-28 17:57

from django.db import migrations, models
import guitarradar.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_guitarpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='body_material',
            field=guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='fingerboard_material',
            field=guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='fingerboard_radius',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='neck_material',
            field=guitarradar.utils.fields.DescriptiveCharField(choices=[('AD', 'Alder'), ('AS', 'Ash'), ('MG', 'Mahogany'), ('EB', 'Ebony'), ('RW', 'Rosewood'), ('MP', 'Maple'), ('RM', 'Roasted Maple'), ('FM', 'Flamed Maple'), ('QM', 'Quilted Maple'), ('PO', 'Poplar'), ('BW', 'Basswood'), ('OT', 'Other')], max_length=2),
        ),
    ]
