# Generated by Django 3.2.9 on 2021-12-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_auto_20211128_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='construction',
            field=models.CharField(choices=[('BO', 'Bolt-on'), ('SN', 'Set neck'), ('NT', 'Neck-thru'), ('ST', 'Set-thru')], default='BO', max_length=2),
            preserve_default=False,
        ),
    ]
