# Generated by Django 3.2.9 on 2021-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0005_guitar_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='bridge',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='guitar',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pickup',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
