# Generated by Django 3.2.9 on 2022-01-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0006_auto_20220111_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'get_latest_by': 'created', 'ordering': ['name', '-modified']},
        ),
    ]
