# Generated by Django 3.2.9 on 2022-01-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0007_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridge',
            options={'get_latest_by': 'created', 'ordering': ['brand', 'model_name']},
        ),
        migrations.AlterModelOptions(
            name='guitar',
            options={'get_latest_by': 'created', 'ordering': ['brand', 'model_name']},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={'get_latest_by': 'created', 'ordering': ['brand', 'model_name']},
        ),
    ]
